name: Build and Deploy

on:
  workflow_dispatch: 
  push:
    branches:
      - main
    path: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --prod
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist
  
  # deployment:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment: dev

  #   steps:
  #   - name: Download build artifacts
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist
  #       path: ./dist
    
