name: build and deploy webapp
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
  push:
    branches: ['master']
    paths: 
    - '/src/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkou code
        uses: actions/checkout@v2 

      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with: 
          node-version: '14' 

      - name: INSTALL dependencies
        run: npm install 

      - name: build webapp
        run: ng build 