name: build and deploy webapp
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: 'src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Setup Node.js
        uses: actions/setup-node@v3 
        with: 
          node-version: '18.x' 

      - name: INSTALL dependencies
        run: npm install 

      - name: build webapp
        run: npm run build --dev

      - name: Upload build artifacts  
        uses: actions/upload-artifact@v2
        with:
          name: artifact-frontend-${{ github.run_number }}
          path: ./dist

  deployment:
    runs-on: ubuntu-latest
    needs: build
    environment: devolop

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact-frontend-${{ github.run_number }}
        path: ./dist

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: copy web site in s3 bucket
      run: aws s3 sync ./dist/viseopipeline-clp s3://viseopipeline-bkr --delete